import {SamuraiViewModel} from "./SamuraiViewModel";

/**
 * PostSamuraiReqDTO is a type alias for a subset of the SamuraiViewModel type.
 * You can use this type to define the shape of the request body for a POST request to the /samurais endpoint.
 *
 * For example, this kind of request would be used to create a new Samurai.
 *
 * @example
 * POST /samurais, body: {name: "Kikuchiyo"}
 *
 * @remarks
 *
 * Id is not required because it is generated by the database.
 */
export type PostSamuraiReqDTO = Omit<SamuraiViewModel, "id">

/**
 * PostSamuraiResDTO is a type alias for a union of the SamuraiViewModel type and an object with a message property.
 * You can use this type to define the shape of the response for a POST request to the /samurais endpoint.
 *
 * For successful requests, the response will be a SamuraiViewModel object with a message property.
 *
 * @example
 * { message: "Samurai created", samurai: { id: 1, name: "Kikuchiyo"}}
 *
 * For unsuccessful requests, the response will be an object with a message property.
 *
 * @example
 * { message: "Samurai name is required" } | { message: "Samurai with this name already exists }
 */
export type PostSamuraiResDTO = {message: string, samurai: SamuraiViewModel} | {message: string}
